export const GET_DATA = "GET_DATA"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const DELETE_ITEM = "DELETE_ITEM"
export const ADD_ITEM = "ADD_ITEM"
export const UPDATE_ITEM = "UPDATE_ITEM"